### ISSUE TITLE
Updating to Middleman 3.3+

### ISSUE THREAD

**Issue by dikaio** [Aupajo/middleman-pagination#6]
Hi @Aupajo any chance you will be updating your gem to support new middleman builds?

**Comment by Aupajo** [comment]
Hi @dikaio, I'm just updating the gem's dependencies now. Is it not working for you at the moment?

**Comment by dikaio** [comment]
Hi @Aupajo. Gem works great, it was just when I tried using it after I updated to Middleman 3.3.10 the gem through errors because it was still dependent on an older version of middleman & middleman-core. I forked it updated the dependencies and ran it locally, no problems came up but I didn't run any tests :/

Great gem, love it!

**Comment by Aupajo** [comment]
Just shipped a release candidate. Would you be able to double-check it for me?

```
gem "middleman-pagination", "1.2.0.rc1"
```

If it looks good, I'll push `1.2.0`.

**Comment by dikaio** [comment]
checks out! :thumbsup:

**Comment by dikaio** [comment]
Thanks for fast push Pete!

**Comment by Aupajo** [comment]
No problem! Shipped now. :shipit: 

```
gem "middleman-pagination", "~> 1.2"
```
